eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
---
spring:
  profiles: lab-4-adjective
words: I,You,He,She,It

---
spring:
  profiles: lab-4-verb
words: ran,knew,had,saw,bought,car

---
spring:
  profiles: lab-4-article
words: a,the,dum

---
spring:
  profiles: lab-4-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely,sim

---
spring:
  profiles: lab-4-noun
words: boat,book,vote,seat,backpack,partition,groundhog,herb      
      
