eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8010/eureka/
      
---
spring:
  profiles: adjective
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought,car

---
spring:
  profiles: article
words: a,the,dum

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely,sim

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog,herb      
      
---
spring:
  profiles: subject
words: I,You,He,She,It,dunda

